
enum UITextHorizontalAlignment : char
{
    HORIZONTAL_LEFT_TEXT_ALIGNMENT,
    HORIZONTAL_CENTER_TEXT_ALIGNMENT,
    HORIZONTAL_RIGHT_TEXT_ALIGNMENT
};

enum UITextVerticalAlignment : char
{
    VERTICAL_TOP_TEXT_ALIGNMENT,
    VERTICAL_CENTER_TEXT_ALIGNMENT,
    VERTICAL_BOTTOM_TEXT_ALIGNMENT
};